name: flutter_video_editor
description: Flutter application to edit video with the use of the FFMPEG package [see https://pub.dev/packages/ffmpeg_kit_flutter].
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6                       # Used for state management and navigation
  ffmpeg_kit_flutter: ^6.0.3        # Used for video editing
  image_picker: ^1.0.4              # Used for picking images and videos
  mime: ^1.0.4                      # Used for getting mime type of files
  video_thumbnail: ^0.5.3           # Used for getting thumbnails of the picked video
  intl: ^0.19.0                     # Used for formatting date and time
  firebase_core:                    # Used for firebase core
  firebase_auth:                    # Used for firebase authentication with Google
  google_sign_in:                   # Used for google sign in
  http: 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Century Gothic
      fonts:
        - asset: fonts/CenturyGothic-Regular.ttf
        - asset: fonts/CenturyGothic-Bold.ttf
          weight: 700
        - asset: fonts/CenturyGothic-Italic.ttf
          style: italic        
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
