// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_video_editor/shared/core/constants.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDncjBvkd40prB92S52sPr4xXYoC7bcb98',
    appId: '1:535183268782:web:e925ccc7754b401ec2463f',
    messagingSenderId: '535183268782',
    projectId: 'flutter-video-editor',
    authDomain: 'flutter-video-editor.firebaseapp.com',
    storageBucket: 'flutter-video-editor.appspot.com',
    measurementId: 'G-HQXLCRDH3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDBJznM6dCOS1gK1GGc_8iiLRr_bZLps',
    appId: '1:535183268782:android:8f6a555fd2462155c2463f',
    messagingSenderId: '535183268782',
    projectId: 'flutter-video-editor',
    storageBucket: 'flutter-video-editor.appspot.com',
    databaseURL: Constants.databaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVv6I2Vt7EoeGQlZkgjTSz6ddbyOXJ-w',
    appId: '1:535183268782:ios:701508d27c60f79bc2463f',
    messagingSenderId: '535183268782',
    projectId: 'flutter-video-editor',
    storageBucket: 'flutter-video-editor.appspot.com',
    iosBundleId: 'com.example.flutterVideoEditor',
    databaseURL: Constants.databaseUrl,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVv6I2Vt7EoeGQlZkgjTSz6ddbyOXJ-w',
    appId: '1:535183268782:ios:c911d82537fc4752c2463f',
    messagingSenderId: '535183268782',
    projectId: 'flutter-video-editor',
    storageBucket: 'flutter-video-editor.appspot.com',
    iosBundleId: 'com.example.flutterVideoEditor.RunnerTests',
  );
}
